"""add extracted_by

Revision ID: 6a5da8949b65
Revises: bd872f3267bf
Create Date: 2026-10-08 14:45:06.721968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5da8949b65'
down_revision: Union[str, Sequence[str], None] = 'bd872f3267bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_by', sa.String(length=100), nullable=True))

    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_by', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.drop_column('extracted_by')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('extracted_by')

    # ### end Alembic commands ###
